name: client
description: "RedCloud VPN - Next-Gen Anti-Censorship Client for Linux"
publish_to: 'none'

version: 3.5.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # پل ارتباطی فلاتر با هسته باینری راست
  rust_lib_client:
    path: rust_builder
  flutter_rust_bridge: 2.12.0

  # پکیج‌های شبکه و ابزارهای دسکتاپ لینوکس
  http: ^1.6.0
  window_manager: ^0.5.1
  tray_manager: ^0.5.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  # پشتیبانی از آیکون‌های PNG (فرمت استاندارد دسکتاپ و سیستم ترِی لینوکس) و ICO
  assets:
    - assets/app_icon.png
    - assets/app_icon.ico

  uses-material-design: true