// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `assign_child_to_job`, `convert_link_to_outbound`, `get_global_job_object`, `get_safe_work_dir`, `notify_windows_proxy_change`, `process_aether_line`, `resolve_binary_path`, `scan_single_ip`, `set_windows_system_proxy`, `spawn_single_aether_mode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<bool> isConnected() => RustLib.instance.api.crateApiSimpleIsConnected();

Future<bool> isTorConnected() =>
    RustLib.instance.api.crateApiSimpleIsTorConnected();

Future<bool> isPsiphonConnected() =>
    RustLib.instance.api.crateApiSimpleIsPsiphonConnected();

Future<bool> isAetherConnected() =>
    RustLib.instance.api.crateApiSimpleIsAetherConnected();

Future<bool> isHybridConnected() =>
    RustLib.instance.api.crateApiSimpleIsHybridConnected();

Future<bool> isDnsActive() => RustLib.instance.api.crateApiSimpleIsDnsActive();

Future<int> getTorBootstrapProgress() =>
    RustLib.instance.api.crateApiSimpleGetTorBootstrapProgress();

Future<bool> isPsiphonBootstrapDone() =>
    RustLib.instance.api.crateApiSimpleIsPsiphonBootstrapDone();

Future<int> getAetherBootstrapProgress() =>
    RustLib.instance.api.crateApiSimpleGetAetherBootstrapProgress();

Future<bool> isAetherBootstrapDone() =>
    RustLib.instance.api.crateApiSimpleIsAetherBootstrapDone();

Future<String> getAetherStatusText() =>
    RustLib.instance.api.crateApiSimpleGetAetherStatusText();

Future<int> pingDnsServer({required String ip}) =>
    RustLib.instance.api.crateApiSimplePingDnsServer(ip: ip);

Future<int> pingProxyServer({required String host, required int port}) =>
    RustLib.instance.api.crateApiSimplePingProxyServer(host: host, port: port);

Future<String> setSystemDns({
  required String primary,
  required String secondary,
}) => RustLib.instance.api.crateApiSimpleSetSystemDns(
  primary: primary,
  secondary: secondary,
);

Future<String> resetSystemDns() =>
    RustLib.instance.api.crateApiSimpleResetSystemDns();

Future<String> startAetherCore({
  required String binaryPath,
  required String mode,
  required String noize,
  String? warpKey,
  String? team,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartAetherCore(
  binaryPath: binaryPath,
  mode: mode,
  noize: noize,
  warpKey: warpKey,
  team: team,
  useSystemProxy: useSystemProxy,
);

Future<String> stopAetherCore() =>
    RustLib.instance.api.crateApiSimpleStopAetherCore();

/// شروع اتصال هیبریدی کاملاً منطبق بر استاندارد Sing-box 1.10 - 1.14+ با فیلد مدرن address آرایه‌ای
Future<String> startHybridConnection({
  required String singboxPath,
  required String aetherPath,
  required ProxyNode selectedNode,
  required String aetherMode,
  required String aetherNoize,
  String? aetherWarpKey,
  String? aetherTeam,
  required bool useSystemProxy,
  required bool useTunMode,
  required String dnsType,
  required String dnsPrimary,
  required String dnsSecondary,
  String? dnsDotHost,
  String? utlsFingerprint,
}) => RustLib.instance.api.crateApiSimpleStartHybridConnection(
  singboxPath: singboxPath,
  aetherPath: aetherPath,
  selectedNode: selectedNode,
  aetherMode: aetherMode,
  aetherNoize: aetherNoize,
  aetherWarpKey: aetherWarpKey,
  aetherTeam: aetherTeam,
  useSystemProxy: useSystemProxy,
  useTunMode: useTunMode,
  dnsType: dnsType,
  dnsPrimary: dnsPrimary,
  dnsSecondary: dnsSecondary,
  dnsDotHost: dnsDotHost,
  utlsFingerprint: utlsFingerprint,
);

Future<String> stopHybridConnection() =>
    RustLib.instance.api.crateApiSimpleStopHybridConnection();

Future<String> startTorCore({
  required String binaryPath,
  required String countryCode,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartTorCore(
  binaryPath: binaryPath,
  countryCode: countryCode,
  useSystemProxy: useSystemProxy,
);

Future<String> stopTorCore() =>
    RustLib.instance.api.crateApiSimpleStopTorCore();

Future<String> startPsiphonCore({
  required String binaryPath,
  required String countryCode,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartPsiphonCore(
  binaryPath: binaryPath,
  countryCode: countryCode,
  useSystemProxy: useSystemProxy,
);

Future<String> stopPsiphonCore() =>
    RustLib.instance.api.crateApiSimpleStopPsiphonCore();

Future<List<ProxyNode>> runCloudflareScanner({
  required String uuid,
  required String path,
  required String worker,
}) => RustLib.instance.api.crateApiSimpleRunCloudflareScanner(
  uuid: uuid,
  path: path,
  worker: worker,
);

Future<String> startProxyWithNode({
  required String binaryPath,
  required ProxyNode selectedNode,
  required bool useSystemProxy,
  String? customSni,
  required bool enableFragment,
  required bool enableRecordFragment,
  String? tlsSpoof,
  required bool useTunMode,
  required String dnsType,
  required String dnsPrimary,
  required String dnsSecondary,
  String? dnsDohUrl,
  String? dnsDotHost,
  String? utlsFingerprint,
  String? fragmentFallbackDelay,
}) => RustLib.instance.api.crateApiSimpleStartProxyWithNode(
  binaryPath: binaryPath,
  selectedNode: selectedNode,
  useSystemProxy: useSystemProxy,
  customSni: customSni,
  enableFragment: enableFragment,
  enableRecordFragment: enableRecordFragment,
  tlsSpoof: tlsSpoof,
  useTunMode: useTunMode,
  dnsType: dnsType,
  dnsPrimary: dnsPrimary,
  dnsSecondary: dnsSecondary,
  dnsDohUrl: dnsDohUrl,
  dnsDotHost: dnsDotHost,
  utlsFingerprint: utlsFingerprint,
  fragmentFallbackDelay: fragmentFallbackDelay,
);

Future<String> stopProxyCore() =>
    RustLib.instance.api.crateApiSimpleStopProxyCore();

Future<List<ProxyNode>> parseImportLinks({required String input}) =>
    RustLib.instance.api.crateApiSimpleParseImportLinks(input: input);

class ProxyNode {
  final String name;
  final String protocol;
  final String rawUrl;

  const ProxyNode({
    required this.name,
    required this.protocol,
    required this.rawUrl,
  });

  @override
  int get hashCode => name.hashCode ^ protocol.hashCode ^ rawUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyNode &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          protocol == other.protocol &&
          rawUrl == other.rawUrl;
}
